(() => {
  const $ = (s, e=document) => e.querySelector(s), esc = s => String(s).replace(/[&<>"]/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  if (document.body.classList.contains('login-page')) {
    $('#password-toggle').onclick=()=>{let i=$('#admin-password'); i.type=i.type==='password'?'text':'password'};
    $('#forgot-link').onclick=e=>{e.preventDefault();$('#forgot-modal').classList.add('show')}; document.querySelectorAll('[data-forgot-close]').forEach(b=>b.onclick=()=>$('#forgot-modal').classList.remove('show'));
    $('#forgot-form').onsubmit = (event) => {
      event.preventDefault();
      $('#forgot-status').textContent = 'Password resets require the deployment setup secret. See the authentication setup steps in README.md.';
    };
    $('#login-form').onsubmit = async (event) => {
      event.preventDefault();
      const email = $('#admin-email').value.trim();
      const password = $('#admin-password').value;
      const remember = $('.check input').checked;
      const button = $('.login-submit');
      const error = $('#login-error');
      button.disabled = true;
      try {
        const response = await fetch('/api/auth/login', {
          method: 'POST',
          credentials: 'same-origin',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ email, password, remember }),
        });
        const authenticatedUser = response.ok ? await CodeIOAuth.currentUser() : null;
        if (!response.ok) {
          error.textContent = response.status === 400 || response.status === 401
            ? 'Invalid email or password.'
            : 'Sign in is temporarily unavailable.';
          error.classList.add('show');
          return;
        }
        error.classList.remove('show');
        button.textContent = 'Signing in...';
        location.href = authenticatedUser?.role === 'admin' ? 'admin.html' : 'index.html';
      } catch {
        error.textContent = 'Sign in is temporarily unavailable.';
        error.classList.add('show');
      } finally {
        button.disabled = false;
      }
    };
    document.addEventListener('keydown', (event) => {
      if (event.key === 'Escape') $('#forgot-modal').classList.remove('show');
    });
    return;
  }
  if (!$('#app')) return;
  let page='dashboard', activeMessage=1, mobileMessageOpen=false, projectFilter='All', search=''; const D=window.AdminData;
  const icon={dashboard:'▦',projects:'◇',team:'♙',messages:'✉',media:'▧',settings:'⚙'};
  function toast(msg,type='success'){let t=document.createElement('div');t.className='toast '+(type==='error'?'error':'');t.textContent=msg;$('#toast-stack')?.append(t);setTimeout(()=>t.remove(),3500)}
  function save(){D.save();render()}
  function nav(){const s=D.get(), unread=s.messages.filter(x=>x.status==='Unread').length;return `<aside class="sidebar"><a class="admin-brand" href="index.html"><img src="assets/CODE.IO.png" alt="">CODE<span>.</span>IO</a><p class="panel-label">ADMIN PANEL</p><nav class="nav-list">${['dashboard','projects','team','messages','media','settings'].map(n=>`<button class="nav-item ${page===n?'active':''}" data-page="${n}"><i class="nav-icon">${icon[n]}</i>${n[0].toUpperCase()+n.slice(1)}${n==='messages'?`<b class="badge">${unread}</b>`:''}</button>`).join('')}</nav><div class="side-profile"><div class="avatar">${s.profile.initials}</div><div><div class="profile-name">${s.profile.name}</div><div class="profile-role">${s.profile.role}</div></div><button class="dots" data-menu="profile">⋮</button></div></aside><div class="sidebar-overlay"></div>`}
  function header(){let title=page[0].toUpperCase()+page.slice(1);return `<header class="topbar"><div style="display:flex;align-items:center;gap:10px"><button class="icon-btn mobile-trigger" data-action="menu">☰</button><div><div class="crumb">Admin / ${title}</div><h1 class="page-title">${title}</h1></div></div><div class="header-actions"><div class="search-box"><input id="global-search" value="${esc(search)}" placeholder="Search everything…"><div class="search-results"></div></div><button class="icon-btn hide-mobile">♧<span class="noti-dot">3</span></button><div class="avatar">${D.get().profile.initials}</div><button class="dots" data-menu="profile">⋮</button></div></header>`}
  const stats=()=>{let s=D.get();return `<div class="stats">${[['◇',s.projects.length,'Total Projects','+2 this month'],['♙',s.team.length,'Team Members','+1 this month'],['✉',48,'Messages','+12%'],['◉',s.messages.filter(x=>x.status==='Unread').length,'Unread Messages','Needs attention']].map(x=>`<article class="stat-card"><div class="stat-top"><span class="stat-icon">${x[0]}</span><span class="trend">${x[3]}</span></div><div class="stat-num">${x[1]}</div><div class="muted">${x[2]}</div></article>`).join('')}</div>`}
  function dashboard(){let s=D.get();return `<div class="welcome"><div><h2>Good morning, Admin</h2><p>Here's what's happening with your portfolio.</p></div><div class="actions"><button class="primary-btn" data-modal="project">+ Add Project</button><button class="ghost-btn" data-modal="team">+ Add Team Member</button><button class="ghost-btn" data-page="messages">View Messages</button></div></div>${stats()}<div class="section-grid"><section class="card"><div class="card-head"><h3>Recent messages</h3><button class="text-btn" data-page="messages">Open inbox →</button></div><div class="table-wrap"><table><thead><tr><th>Sender</th><th>Subject</th><th>Status</th><th>Date</th><th></th></tr></thead><tbody>${s.messages.map(m=>`<tr><td>${m.name}</td><td>${m.subject}</td><td><span class="status ${m.status.toLowerCase()}">${m.status}</span></td><td>${m.date}</td><td><button class="text-btn" data-message="${m.id}">View</button></td></tr>`).join('')}</tbody></table></div></section><section class="card"><div class="card-head"><h3>Recent projects</h3><button class="text-btn" data-page="projects">View all →</button></div><div class="mini-projects">${s.projects.map(p=>`<div class="mini-project"><img src="${p.image}" alt=""><div><strong>${p.name}</strong><div class="muted">${p.category} · ${p.updated}</div></div><span class="status ${p.status.toLowerCase()}">${p.status}</span></div>`).join('')}</div><div class="card-head"><h3>Quick actions</h3></div><div class="quick-grid"><button class="quick" data-modal="project">+ New project</button><button class="quick" data-modal="team">+ Add member</button><button class="quick" data-page="messages">Open inbox</button><button class="quick" data-page="media">Manage media</button></div></section></div>`}
  function projects(){let s=D.get(), list=s.projects.filter(p=>projectFilter==='All'||p.status===projectFilter);return `<div class="view-head"><div><h2>Projects</h2><p>Manage all projects displayed on the portfolio.</p></div><button class="primary-btn" data-modal="project">+ Add Project</button></div><div class="toolbar"><input id="project-search" placeholder="Search projects…"><div class="tabs">${['All','Published','Draft','Archived'].map(x=>`<button class="tab ${x===projectFilter?'active':''}" data-filter="${x}">${x}</button>`).join('')}</div></div><div class="projects-grid">${list.map(p=>`<article class="card project-card-admin"><img src="${p.image}" alt="${p.name}"><div class="project-info"><span class="status ${p.status.toLowerCase()}">${p.status}</span><h3>${p.name}</h3><div class="muted">${p.category} · Updated ${p.updated}</div><div class="card-actions"><button class="small-btn" data-toast="Preview is ready for public routing.">View</button><button class="small-btn" data-modal="project" data-id="${p.id}">Edit</button><button class="small-btn delete" data-confirm="project" data-id="${p.id}">Delete</button></div></div></article>`).join('')||'<p class="muted">No projects found.</p>'}</div>`}
  function team(){let s=D.get();return `<div class="view-head"><div><h2>Team</h2><p>Manage the people displayed on the portfolio.</p></div><button class="primary-btn" data-modal="team">+ Add Member</button></div><div class="team-grid">${s.team.map(m=>`<article class="card team-card"><div class="avatar">${m.initials}</div><h3>${m.name}</h3><div class="muted">${m.role}</div><p>${m.bio}</p><div class="card-actions"><button class="small-btn" data-modal="team" data-id="${m.id}">Edit</button><button class="small-btn delete" data-confirm="team" data-id="${m.id}">Delete</button><button class="small-btn" data-toast="Drag ordering will be connected to portfolio publishing.">↕ Reorder</button></div></article>`).join('')}</div>`}
  function messages(){let s=D.get(),m=s.messages.find(x=>x.id===activeMessage)||s.messages[0];return `<div class="view-head"><div><h2>Messages</h2><p>Conversations from your portfolio contact form.</p></div><button class="primary-btn" data-modal="compose">Compose Message</button></div><section class="card inbox ${mobileMessageOpen?'message-open':''}"><aside class="conversation-list"><div class="inbox-search"><input placeholder="Search messages…"></div><div class="tabs" style="padding:8px">${['All','Unread','Replied','Archived'].map(x=>`<button class="tab ${x==='All'?'active':''}">${x}</button>`).join('')}</div>${s.messages.map(x=>`<div class="conversation ${x.id===m.id?'active':''}" data-message="${x.id}"><div class="conv-row"><span class="conv-name">${x.name}</span><span class="muted">${x.time}</span></div><div class="conv-subject">${x.subject}</div><div class="conv-preview">${x.preview}</div></div>`).join('')}</aside><div class="message-pane"><div class="message-header"><div><h3>${m.name}</h3><p>${m.email} · ${m.subject}</p></div><div><button class="small-btn" data-reply>Reply</button><button class="small-btn" data-action="unread">Mark unread</button><button class="small-btn delete" data-confirm="message" data-id="${m.id}">Delete</button></div></div><div class="thread">${m.thread.map(b=>`<div class="bubble ${b.from==='CODE.IO'?'admin':''}"><div class="bubble-meta">${b.from} · ${b.time}</div>${b.text}</div>`).join('')}</div><form class="composer" id="reply-form"><textarea placeholder="Write your reply…"></textarea><div class="compose-actions"><span class="muted">⌕ Attach · Aa Format · ☺ Emoji</span><div><button type="button" class="ghost-btn" data-toast="Draft saved.">Save Draft</button><button class="primary-btn">Send Reply</button></div></div></form></div></section>`}
  function media(){let s=D.get();return `<div class="view-head"><div><h2>Media</h2><p>Organize images and documents for your portfolio.</p></div><button class="primary-btn" data-modal="media">Upload Media</button></div><div class="tabs" style="margin-bottom:14px"><button class="tab active">All</button><button class="tab">Images</button><button class="tab">Documents</button></div><div class="media-grid">${s.media.map(x=>`<article class="card media-card"><div class="media-preview">${x.image?`<img src="${x.image}" alt="">`:'PDF'}</div><div class="media-info"><strong>${x.name}</strong><div class="muted">${x.type} · ${x.size} · ${x.date}</div><div class="card-actions"><button class="small-btn" data-toast="Demo URL copied to clipboard.">Copy URL</button><button class="small-btn delete" data-confirm="media" data-id="${x.id}">Delete</button></div></div></article>`).join('')}</div>`}
  function settings(){let p=D.get().profile;return `<div class="view-head"><div><h2>Settings</h2><p>Configure your admin workspace and public portfolio details.</p></div></div><div class="settings"><section class="card"><h3>Profile</h3><div class="form-grid"><label class="field-label">Name<input class="form-control" value="${p.name}"></label><label class="field-label">Email<input class="form-control" value="${p.email}"></label></div><button class="primary-btn" style="margin-top:15px" data-toast="Profile changes saved.">Save Changes</button></section><section class="card"><h3>Account</h3><div class="toggle-row">Two-factor authentication <input class="switch" type="checkbox"></div><div class="toggle-row">Active sessions <button class="small-btn" data-toast="You have one active demo session.">Manage</button></div><button class="ghost-btn" data-toast="Password change is ready for backend integration.">Change Password</button></section><section class="card"><h3>Appearance</h3><div class="toggle-row">Dark theme <select class="form-control"><option>Dark</option><option>Light</option><option>System</option></select></div><div class="toggle-row">Compact sidebar <input class="switch" type="checkbox"></div><div class="toggle-row">Animations <input class="switch" type="checkbox" checked></div></section><section class="card"><h3>Notifications</h3>${['Email notifications','New message notifications','Project notifications','Admin alerts'].map(x=>`<div class="toggle-row">${x}<input class="switch" type="checkbox" checked></div>`).join('')}</section><section class="card"><h3>Website</h3><div class="form-grid"><label class="field-label">Portfolio title<input class="form-control" value="CODE.IO"></label><label class="field-label">Contact email<input class="form-control" value="updrafttech.ai@gmail.com"></label></div><button class="primary-btn" style="margin-top:15px" data-toast="Website settings saved.">Save Changes</button></section></div>`}
  function view(){return ({dashboard,projects,team,messages,media,settings}[page])()}
  function render(){ $('#app').innerHTML=nav()+`<main class="main">${header()}<div class="content">${view()}</div></main>`; bind(); }
  function modal(type,id){let s=D.get(), item=type==='project'?s.projects.find(x=>x.id==id):type==='team'?s.team.find(x=>x.id==id):null, title=item?'Edit ':type==='compose'?'Compose Message':type==='media'?'Upload Media':'Add ';title+=item?(type==='project'?'Project':'Team Member'):type==='team'?'Team Member':''; let fields=type==='project'?[['title','Project Title',item?.name],['category','Category',item?.category],['description','Short Description',item?.description]]:type==='team'?[['name','Name',item?.name],['role','Role',item?.role],['bio','Bio',item?.bio]]:type==='compose'?[['to','To',''],['subject','Subject',''],['message','Message','']]:[];let html=`<div class="modal-layer show"><form class="modal" id="modal-form" data-type="${type}" data-id="${id||''}"><div class="modal-head"><div><h2>${title}</h2><p class="muted">Frontend demo — ready for future API integration.</p></div><button class="close" type="button" data-close>×</button></div>${type==='media'?'<div class="upload-mini">Drop files here or <b>browse files</b><br><small>Mock upload will add a media item</small></div>':`<div class="form-grid">${fields.map(f=>`<label class="field-label">${f[1]}${f[0]==='description'||f[0]==='bio'||f[0]==='message'?`<textarea class="form-control" name="${f[0]}" required>${f[2]||''}</textarea>`:`<input class="form-control" name="${f[0]}" value="${f[2]||''}" required>`}</label>`).join('')}</div>${type==='project'?'<div class="upload-mini" style="margin-top:15px">Project Cover · Drag & drop upload UI · Browse files</div>':''}` }<div class="modal-actions"><button type="button" class="ghost-btn" data-close>Cancel</button><button class="primary-btn">${type==='project'?(item?'Save Changes':'Publish Project'):type==='team'?'Save Member':type==='compose'?'Send':'Upload Media'}</button></div></form></div>`;document.body.insertAdjacentHTML('beforeend',html);$('#modal-form').onsubmit=submitModal}
  function submitModal(e){e.preventDefault();let f=e.currentTarget,type=f.dataset.type,s=D.get(),v=Object.fromEntries(new FormData(f));if(type==='project'){let x=s.projects.find(x=>x.id==f.dataset.id);if(x)Object.assign(x,{name:v.title,category:v.category,description:v.description});else s.projects.unshift({id:D.id(),name:v.title,category:v.category,status:'Published',updated:'Just now',image:'assets/hero.jpg',description:v.description});toast(x?'Project updated successfully.':'Project added successfully.')}if(type==='team'){let x=s.team.find(x=>x.id==f.dataset.id);if(x)Object.assign(x,v);else s.team.unshift({id:D.id(),...v,initials:v.name.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()});toast(x?'Team member updated.':'Team member added.')}if(type==='compose'){if(!v.to||!v.subject||!v.message)return toast('Please complete all required fields.','error');s.messages.unshift({id:D.id(),name:v.to,email:v.to,subject:v.subject,preview:v.message,time:'Now',date:'Today',status:'Replied',initials:'TO',thread:[{from:'CODE.IO',time:'Now',text:v.message}]});toast('Message sent successfully.')}if(type==='media'){s.media.unshift({id:D.id(),name:'new-upload.jpg',type:'Image',size:'1.2 MB',date:'Now',image:'assets/hero.jpg'});toast('Media uploaded successfully.')}D.save();$('.modal-layer').remove();render()}
  function confirmDelete(type,id){let names={project:'project',team:'team member',message:'message',media:'media item'},layer=document.createElement('div');layer.className='modal-layer show';layer.innerHTML=`<div class="modal" style="max-width:400px"><div class="modal-head"><div><h2>Delete this ${names[type]}?</h2><p class="muted">This action cannot be undone.</p></div></div><div class="modal-actions"><button class="ghost-btn" data-close>Cancel</button><button class="danger-btn" data-delete>Delete</button></div></div>`;document.body.append(layer);$('[data-close]',layer).onclick=()=>layer.remove();$('[data-delete]',layer).onclick=()=>{let s=D.get(), key=type==='team'?'team':type==='media'?'media':type==='message'?'messages':'projects';s[key]=s[key].filter(x=>x.id!=id);D.save();layer.remove();toast(`${names[type][0].toUpperCase()+names[type].slice(1)} deleted.`);render()}}
  function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;if(page==='messages')mobileMessageOpen=false;render()});document.querySelectorAll('[data-modal]').forEach(b=>b.onclick=()=>modal(b.dataset.modal,b.dataset.id));document.querySelectorAll('[data-confirm]').forEach(b=>b.onclick=()=>confirmDelete(b.dataset.confirm,b.dataset.id));document.querySelectorAll('[data-message]').forEach(b=>b.onclick=()=>{activeMessage=+b.dataset.message;mobileMessageOpen=true;page='messages';let m=D.get().messages.find(x=>x.id===activeMessage);if(m)m.status='Read';D.save();render()});document.querySelectorAll('[data-toast]').forEach(b=>b.onclick=()=>toast(b.dataset.toast));document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{projectFilter=b.dataset.filter;render()});$('[data-action="menu"]')?.addEventListener('click',()=>{$('.sidebar').classList.add('open');$('.sidebar-overlay').classList.add('show')});$('.sidebar-overlay')?.addEventListener('click',()=>{$('.sidebar').classList.remove('open');$('.sidebar-overlay').classList.remove('show')});document.querySelectorAll('[data-menu="profile"]').forEach(b=>b.onclick=()=>profileMenu());$('#global-search')?.addEventListener('input',e=>{let q=e.target.value.toLowerCase(),s=D.get(),r=$('.search-results');if(!q){r.classList.remove('show');return}let all=[...s.projects.map(x=>['PROJECTS',x.name,'projects']),...s.team.map(x=>['TEAM',x.name,'team']),...s.messages.map(x=>['MESSAGES',x.name+' — '+x.subject,'messages'])].filter(x=>x[1].toLowerCase().includes(q));r.innerHTML=all.map(x=>`<div class="result" data-go="${x[2]}"><small>${x[0]}</small>${x[1]}</div>`).join('')||'<div class="result muted">No results</div>';r.classList.add('show');r.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>{page=x.dataset.go;render()})});$('#reply-form')?.addEventListener('submit',e=>{e.preventDefault();let input=$('textarea',e.currentTarget),text=input.value.trim(),m=D.get().messages.find(x=>x.id===activeMessage);if(!text)return;if(!m.thread)m.thread=[];m.thread.push({from:'CODE.IO',time:'Just now',text});m.status='Replied';D.save();toast('Message sent successfully.');render()});$('[data-reply]')?.addEventListener('click',()=>$('.composer textarea').focus());$('[data-action="unread"]')?.addEventListener('click',()=>{let m=D.get().messages.find(x=>x.id===activeMessage);m.status='Unread';D.save();toast('Marked as unread.');render()});$('#project-search')?.addEventListener('input',e=>{document.querySelectorAll('.project-card-admin').forEach(x=>x.style.display=x.textContent.toLowerCase().includes(e.target.value.toLowerCase())?'':'none')})}
  function profileMenu(){let l=document.createElement('div');l.className='modal-layer show';l.innerHTML='<div class="modal" style="max-width:300px"><div class="modal-head"><h2>Account</h2><button class="close" data-close>×</button></div><button class="quick" data-profile>Profile</button><button class="quick" data-settings>Settings</button><button class="danger-btn" style="width:100%;margin-top:10px" data-logout>Logout</button></div>';document.body.append(l);$('[data-close]',l).onclick=()=>l.remove();$('[data-profile]',l).onclick=()=>location.href='profile.html';$('[data-settings]',l).onclick=()=>{l.remove();page='settings';render()};$('[data-logout]',l).onclick=async()=>{await CodeIOAuth.logout();location.href='index.html'}}
  document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.modal-layer.show').forEach(x=>x.remove())}); CodeIOAuth.currentUser().then(user=>{if(!user)location.replace('admin-login.html');else if(user.role!=='admin')location.replace('index.html');else render()}); window.toast=toast;
})();
